// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoFodBfIPiHq-6zu1m45ovNagmsKgZBPM',
    appId: '1:546098499306:web:7743fba6d0f436cfe6d193',
    messagingSenderId: '546098499306',
    projectId: 'easychat-98a81',
    authDomain: 'easychat-98a81.firebaseapp.com',
    storageBucket: 'easychat-98a81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIcdvgtC8MW0lbL4iKaeT6odbcrF4e1Do',
    appId: '1:546098499306:android:5efa762d5722608ee6d193',
    messagingSenderId: '546098499306',
    projectId: 'easychat-98a81',
    storageBucket: 'easychat-98a81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuWwBaywNxCK1XdhphCRkng5fHimlC05w',
    appId: '1:546098499306:ios:985d4272d99e024ce6d193',
    messagingSenderId: '546098499306',
    projectId: 'easychat-98a81',
    storageBucket: 'easychat-98a81.appspot.com',
    iosClientId: '546098499306-0i3buipsfs8qt0u6it909gb5fb4252gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuWwBaywNxCK1XdhphCRkng5fHimlC05w',
    appId: '1:546098499306:ios:985d4272d99e024ce6d193',
    messagingSenderId: '546098499306',
    projectId: 'easychat-98a81',
    storageBucket: 'easychat-98a81.appspot.com',
    iosClientId: '546098499306-0i3buipsfs8qt0u6it909gb5fb4252gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
